### ISSUE TITLE
ODBC v0.5.2 is incompatible with DataFrames v0.11 and prevents a DataFrames upgrade to v0.11.

### ISSUE THREAD

**Issue by ltf-canada** [JuliaDatabases/ODBC.jl#175]

**Comment by ValdarT** [comment]
The master is compatible with the new DataFrames so I think they just need to tag a new release. In the meantime you can install and use the mater with `Pkg.checkout("ODBC")`.

**Comment by omus** [comment]
Addressed in ODBC v0.6.0.
