### ISSUE TITLE
LoadError: you must implement endof(WeakRefString{UInt8})

### ISSUE THREAD

**Issue by takkaaa** [JuliaDatabases/ODBC.jl#188]
Hi,

I am getting this error message when trying to enter String values with current ODBC master and WeakRefStrings 0.4.2.

I am not sure if I should post it here or in WeakRefStrings...

Thanks,
Piotr

**Comment by omus** [comment]
Looks like this issue already exists in WeakRefStrings: https://github.com/quinnj/WeakRefStrings.jl/issues/25

**Comment by quinnj** [comment]
This should be fixed in the new release;
