### ISSUE TITLE
Silent error when extracting text from SQL Server

### ISSUE THREAD

**Issue by JockLawrie** [JuliaDatabases/ODBC.jl#192]
Hi there,

I am using ODBC 0.6.0 and running the following query against a SQL Server database:
```julia
tbl = ODBC(con, "select Id, ReactionDescription from SomeTable where Id=12345")
```
The result is a `DataFrame` with 1 row, but `tbl[1, :ReactionDescription]` is `""`, which is incorrect. I should get a string with length 411. When I try other `Id` values I usually (but not always) get the correct string truncated to 255 characters. The SQL Server data type is `nvarchar(1000)`.

As a workaround I run the following query:
```julia
tbl = ODBC(con, "select Id, [ReactionDescription] = CAST(ReactionDescription as TEXT) from SomeTable where Id=12345")
```
Now I get the correct result, which is:
`"From ED notes\r\n8/52 old baby presents with excessive crying and significantly poor feeding for the last 2/7 since her 6/52 immunisations on Friday. This is on a background of chronic poor feeding and poor weight gain\r\n \r\n- Increased crying since immunsations\r\n- Decreased feeding compared to normal, only taking 20-30mls every 4-5hrs\r\n- Not waking for feeds\r\n- No vomiting or diarrhoea\r\n- No fevers\r\n- BM 1/week"`

My question is: Why doesn't the original query return a string truncated to 255 characters?

I don't think the newline characters are causing an issue here, as many of the other `Id` values contain these characters.

Cheers,
Jock

**Comment by quinnj** [comment]
Sorry this issue didn't get any attention for a long time; a big overhaul of the package was just merged that probably fixed any issue that was causing this; if you're able to try the same query again, that'd be great to check.
