### ISSUE TITLE
ODBC can't determine DSN settings for Redshift

### ISSUE THREAD

**Issue by ValdarT** [JuliaDatabases/ODBC.jl#198]
I have an Amazon Redshift connection defined in ODBC Data Source Administrator on Windows 10 machine. When I try to connect to it, I get the following error with Julia and ODBC:
```
using ODBC
dsn = ODBC.DSN("Redshift")

[ODBC] 28000: [Amazon][DSI] (20032) Required setting 'UID' is not present in the connection settings.
ODBC.ODBCError("ODBC.API.SQLConnect(dbc, connectionstring, username, password) failed; return code: -1 => SQL_ERROR")

Stacktrace:
 [1] #DSN#3(::Bool, ::Type{T} where T, ::String, ::String, ::String) at C:\Users\Valdar\.julia\v0.6\ODBC\src\ODBC.jl:65
 [2] ODBC.DSN(::String) at C:\Users\Valdar\.julia\v0.6\ODBC\src\ODBC.jl:130
```

It works if I specify the username manually
```
dsn = ODBC.DSN("Redshift", "myusername")
```

For comparison, using this source works fine in R.
```
library(DBI)
dsn <- dbConnect(odbc::odbc(), dsn = "Redshift") # works
```

I'm on Julia `v0.6.2` and ODBC `v0.6.0`.

**Comment by ValdarT** [comment]
Still having the issue, this time on OSX and ODBC v0.8.1.
`ODBC.dsns()` lists the Redshift connection but `dsn = ODBC.DSN("Redshift")` does not work, complains about `[unixODBC][Amazon][DSI] (20032) Required setting 'UID' is not present in the connection settings.` and if provided then `...'PWD' is not present...`. Error comes from `.julia/packages/ODBC/KFiOK/src/ODBC.jl:122`
Everything works fine in R (odbc) and Python (pyodbc).

**Comment by quinnj** [comment]
Fix for this is in https://github.com/JuliaDatabases/ODBC.jl/pull/264
