### ISSUE TITLE
Can't save SQLTimestamp column with Feather.jl

### ISSUE THREAD

**Issue by non-Jedi** [JuliaDatabases/ODBC.jl#202]
I don't really know enough about Julia's conversion system to know whether this is an issue that should be raised over here or on the Feather.jl repo, but it seems like I should be able to create a DataFrame with ODBC.jl, manipulate it, and save the result with Feather.jl without having to broadcast the `Dates.DateTime` constructor over a column. It looks like this doesn't happen because Feather.jl has an explicitly defined set of concrete Dates types it can take as input?

**Comment by quinnj** [comment]
ODBC.jl (on master) now returns `DateTime` by default from queries.
