### ISSUE TITLE
Support parameterized and prepared queries which return rows of data

### ISSUE THREAD

**Issue by timotaularson** [JuliaDatabases/ODBC.jl#210]
This would be the next step beyond [Issue#15](https://github.com/JuliaDatabases/ODBC.jl/issues/15) to support queries which return rows of data.

**Comment by TimoLarson** [comment]
Added a PR for this: https://github.com/JuliaDatabases/ODBC.jl/pull/228

**Comment by quinnj** [comment]
Implemented in #263
