### ISSUE TITLE
ccall: could not find function SQLDriversW in library 

### ISSUE THREAD

**Issue by amillscampisi** [JuliaDatabases/ODBC.jl#218]
Running Julia 1.0.2 on an Amazon Linux 2 EC2 with ODBC v0.8.1. I am usually Jupyter Lab as the IDE. After running the following code, I get the error below:

> import Pkg
> Pkg.build("ODBC")
> 
> import ODBC
> 
> ODBC.drivers()

> ccall: could not find function SQLDriversW in library 
> 
> Stacktrace:
>  [1] SQLDrivers at /home/ec2-user/.julia/packages/ODBC/KFiOK/src/API.jl:73 [inlined]
>  [2] drivers() at /home/ec2-user/.julia/packages/ODBC/KFiOK/src/ODBC.jl:75
>  [3] top-level scope at In[7]:1

**Comment by stroumphc** [comment]
Facing the same issue, any update about it?

**Comment by stroumphc** [comment]
This happens if no driver is found. Had this issue when Dockerizing some code written in Julia, the issue is resolved by installing à driver at the machine.

**Comment by davygarg** [comment]
I am having the same issue . 

ERROR: ccall: could not find function SQLDriversW in library 

Stacktrace:
 [1] SQLDrivers at /root/.julia/packages/ODBC/mb61L/src/API.jl:73 [inlined]
 [2] drivers() at /root/.julia/packages/ODBC/mb61L/src/ODBC.jl:72
 [3] top-level scope at none:0

Trying Julia to connect to MSSQL Database.
