### ISSUE TITLE
Handling of GUID on MS SQL

### ISSUE THREAD

**Issue by RobLW** [JuliaDatabases/ODBC.jl#221]
When I am pulling data back from a MS SQL server 2012, it will contain columns with GUID values in it. But the handling of these info is strange, where I would expect it to be treated as text for ease of use and linking of data, its instead coming back with values like "

ODBC.API.SQLGUID(0x002960ff,   0x3ad1, 0x49c3, (0x82, 0x50, 0xd7, 0xbd, 0x4b, 0x9d, 0xdc, 0xb7))
--

"
Spaces on each end included.

Is this expected normal behaviour for Julia, as it's not what I am use to from other languages?

**Comment by quinnj** [comment]
On master, we now return the `SQL_GUID` type as a `UUID`, which is a `Base` type for representing uuids.
