### ISSUE TITLE
ODBC load won't work

### ISSUE THREAD

**Issue by ilang6** [JuliaDatabases/ODBC.jl#222]
Hi ,

I trying to upload a dataframe to my SQL SERVER 2017.
I have the latest FreeTDS version (0.91) on Debian GNU/Linux version 9 , I'm running inside a docker container  
 and I'm using the following command:

 ` ODBC.load!(db,"database.[dbo].[odbc_test]",df)`

And I get the following error:

> [ODBC] IM001: [unixODBC][Driver Manager]Driver does not support this function

But when I use python to upload data everything work.
I use the following command 

`from sqlalchemy import create_engine
import pandas as pd
engine = create_engine('mssql+pyodbc://user:password@servername?driver=FreeTDS')
df.to_sql(name='odbc_test',schema ='[dbo]',index =False,con=engine)`

please help

**Comment by quinnj** [comment]
Yeah, the previous `ODBC.load` function was using some very specific ODBC functions that, it turns out, a lot of drivers don't implement. I'm marking this issue as 1.0 to ensure we figure out a more general solution before tagging the 1.0 release.
