### ISSUE TITLE
ODBC crash Julia

### ISSUE THREAD

**Issue by ronisbr** [JuliaDatabases/ODBC.jl#223]
Hi!

I am seeing a strange crash in Julia. If I use this query:

```
    query = """
    SELECT PDateTime, PData
    FROM table
    WHERE CAST(PDateTime AS BIGINT)
    BETWEEN """ * date_i * " AND " * date_f
```

It works fine. However the following one:

```
    query = """
    SELECT PData, PDateTime
    FROM table
    WHERE CAST(PDateTime AS BIGINT)
    BETWEEN """ * date_i * " AND " * date_f
```

crashes Julia with the following message:

```
signal (11): Segmentation fault: 11
in expression starting at no file:0
_platform_memmove$VARIANT$Haswell at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 55432700 (Pool: 55421898; Big: 10802); GC: 121
[1]    1171 segmentation fault  julia
```

`PData` is of type `image` and `PDateTime` is of type `char(16)`.

**Comment by ronisbr** [comment]
Moreover, if I add some additional fields to `SELECT`, like another column of type `varchar`, I also see the crash.

**Comment by ronisbr** [comment]
I think I found the problem. `PData` is huge. If I divide the query into two, one with `PDateTime` and `PData` and other with `PDateTime` and the remaining fields, then it works. It should be related to a memory leak or something.

**Comment by ronisbr** [comment]
By the way, when I `SELECT *` in this table, Julia crases. However, if I use pyodbc it works fine, then it must be a memory leak or something... I am trying to figure out but with no luck yet.

**Comment by ronisbr** [comment]
One good news, and one bad news.

The good is that after my last PR, I get not more crashes. Hence, if I do `SELECT *` it does not crash. However, the data which is processed by `function cast!(::Type{API.Long{Union{T, Missing}}}, source, col) where {T}` is not copied. I just see `0x00`. On the other hand, if I type every single column in `SELECT`, then it works fine.

**Comment by quinnj** [comment]
@ronisbr , very sorry for never responding here; I remember seeing the posts and you making a little progres, but then it must have slipped by my radar. If you're still interested, I'd like to help debug this and figure out what's going on. Just let me know and maybe we can find a time to jump on the julia slack to do a chat debug session.

**Comment by ronisbr** [comment]
Hi @quinnj 

No problem!

Unfortunately I do not have access anymore to the database that was showing the problem. However, I will try to simulate something like I had to try to reproduce the error. If I am successful, then we can schedule this debugging session :)

**Comment by quinnj** [comment]
Great; yes, please let me know if you can reproduce and I'm happy to help.

**Comment by quinnj** [comment]
A similar set of issues have been fixed on master (where way too much memory was being requested to process results), so closing this as fixed.
