### ISSUE TITLE
How to query data encoded in GBK from SQL Server 

### ISSUE THREAD

**Issue by headtrain** [JuliaDatabases/ODBC.jl#227]
I wanna query data encoded in GBK from SQL Server via:

df=ODBC.query(dsn,"select * from ...")

Due to the data containing Chinese Charactors,in other words,it is encoded in GBK,the query result of DataFrame is like"\xcd\xf2\xbf\xc6\xc6\xf3ҵ\xb9ɷ\xdd\xd3\xd0\xcf\u7b9\xab˾ "，how can I get the raw data in Chinese?
Thanks a lot!
Headtrain

**Comment by quinnj** [comment]
This should be fixed on master; we're even testing it now! https://github.com/JuliaDatabases/ODBC.jl/blob/a8b1148ae7573b25615d468b7a53198d89ab8631/test/runtests.jl#L64
