### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by kskoeld** [JuliaDatabases/ODBC.jl#232]
Documentation links point to http://juliadatabases.github.io/ODBC.jl/stable/
Latest version is 0.8.2 - however the documentation seems to be for a much older version.
Example: ODBC.listdsns() in docs => ODBC.dsns() in 0.8.2

**Comment by nslocum** [comment]
yup, it looks like the docs have been updated but not published
https://github.com/JuliaDatabases/ODBC.jl/blob/master/docs/src/index.md

**Comment by quinnj** [comment]
Docs have been updated on current master: http://juliadatabases.github.io/ODBC.jl/latest/
