### ISSUE TITLE
Source and Sink types

### ISSUE THREAD

**Issue by mcawte** [JuliaDatabases/ODBC.jl#242]
The documentation gives the example
```
# return result as a csv file
using CSV
csv = ODBC.query(dsn, "select * from cool_table", CSV.Sink, "cool_table.csv")
```

which no longer works. From what I can see, this functionality was given by the code here:
https://github.com/JuliaDatabases/ODBC.jl/blob/v0.7.0/src/Sink.jl
https://github.com/JuliaDatabases/ODBC.jl/blob/v0.7.0/src/Source.jl

The Sink.jl and Source.jl files are not present in versions beyond 0.7.0. Were these files neglected when the transition to Julia 1.0 happened, or has there been a reshuffling of functions with the documentation lagging behind?

**Comment by quinnj** [comment]
The docs have been updated as of #263
