### ISSUE TITLE
Compatibility with DataFrames 0.19

### ISSUE THREAD

**Issue by bharlander** [JuliaDatabases/ODBC.jl#243]
Troubleshooting with @bkamins today, we found that DataFrames newest version 0.19 is not listed as compatible with ODBC 0.8.3 and prevented the upgrade.

**Comment by bkamins** [comment]
CC @quinnj (I see that you committed to this package so you might know if changing DataFrames.jl version will break anything or not). Unfortunately I never used ODBC.jl

**Comment by quinnj** [comment]
Yep, easy fix. I just bumped the DataFrames dependency version and tagged a new release.
