### ISSUE TITLE
ODBC.execute! not working

### ISSUE THREAD

**Issue by JeromieWeatherburn** [JuliaDatabases/ODBC.jl#247]
Hi everyone,
I have been trying to replicate the example in the ODBC.jl documentation using the 
ODBC.prepare & ODBC.execute! functions.
Unfortunatley, I'm getting and error.
I have established connections via the ODBC Data Source Administrator, and have ensured READWRITE is selected. The ANSI options are turned on (though I don't know what this means).
I'm accessing a local SQL Server.

LOCAL = ODBC.DSN("DESKTOP-S4DHG40")
stmt = ODBC.prepare(LOCAL, "INSERT INTO dbo.cool_table VALUES(?, ?, ?)")

# a DataFrame with data we'd like to insert into a table
df = DataFrame(col1=[1,2,3], col2=[4.0, 5.0, 6.0], col3=["hey", "there", "sailor"])

for row = 1:size(df, 1)
    # each time we execute the `stmt`, we pass another row to be bound to the parameters
    ODBC.execute!(stmt, [df[row, x] for x = 1:size(df, 2)])
end
Result is : 
ODBC.ODBCError("API.SQLExecute(stmt) failed; return code: -1 => SQL_ERROR")

I then try manually;
for row in eachrow(df)
           println(row)
           col1 = row[:col1]
           col2 = row[:col2]
           col3 = row[:col3]
           ODBC.execute!(LOCAL, "INSERT INTO dbo.cool_table (col1, col2, col3) VALUES ($col1, $col2, '$col3')")
       end

Result is : 
ODBC.ODBCError("API.SQLExecute(stmt) failed; return code: -1 => SQL_ERROR")

Wondering if anyone has some thoughts on what I may be doing wrong. For example my set up doesn't require a username and password at present (could this be an issue).

Sorry if a NOOB question.
Thanks

**Comment by quinnj** [comment]
Sorry for the slow response here. Your attempts were close and a new package [DBInterface.jl](https://github.com/JuliaDatabases/DBInterface.jl) has defined a consistent interface for this kind of thing. For database packages (including ODBC.jl 1.0), you can do `DBInterface.execute(stmt, (param1, param2, param3))`. There's also a way to pass multiple rows of parameters to be executed like `DBInterface.executemany(stmt, (params1, params2, params3))` where each `paramsX` is an array of values. So in the case of DataFrame, you could do:
```julia
stmt = DBInterface.prepare(conn, "INSERT INTO dbo.cool_table (col1, col2, col3) VALUES (?, ?, ?)")
DBInterface.executemany(stmt, (df.col1, df.col2, df.col3))
```
