### ISSUE TITLE
ODBC.query on MS Access (mdb) databases hangs or restarts the kernel

### ISSUE THREAD

**Issue by PaulMainwood** [JuliaDatabases/ODBC.jl#252]
On Julia 1.3 with DataFrames 0.20

Pulling from an Access database (e.g.,  with O'Reilly's example bibliography database available here: [https://resources.oreilly.com/examples/9780735620599-files/blob/master/Databases/Biblio.mdb], the default ODBC query (that is, the sink to a DataFrame) hangs or restarts the kernel.

This may be related to the Tables.jl interface, since if you ask for a ODBC.Query (rather than ODBC.query), this returns an ODBC.query type. 

However, when you try to send this into a DataFrame (or to a CSV write, or SQLite), then this hangs or restarts the kernel.

```
import ODBC
dsn = ODBC.DSN("Driver={Microsoft Access Driver (*.mdb, *.accdb)}; Dbq=Biblio.mdb")
r = ODBC.Query(dsn, "select * from Titles") #This returns an ODBC.Query type object
df = DataFrame(r) #This restarts the kernel

r = ODBC.query(dsn, "select * from Titles") #This restarts the kernel
```

**Comment by quinnj** [comment]
Hmmm, I don't seem to have a way to reproduce this; my access version says the file is too old to load. It's perhaps a query with a ton of columns? Is there a way for you to find out how many columns are in the `Titles` table?

**Comment by PaulMainwood** [comment]
Don't think sure that's the issue - the "Titles" table has eight columns (and 8570 rows FWIW)

**Comment by quinnj** [comment]
Ok, I was able to get the file and test using the 32-bit access driver on Windows. While it takes a while (the access driver seems to be very slow no matter the table), I can successfully load the `Titles` table into a DataFrame w/o issues. (it took probably 5 minutes or so to load into a DataFrame).
