### ISSUE TITLE
DataFrames compatibility

### ISSUE THREAD

**Issue by tobi-lipede-oodle** [JuliaDatabases/ODBC.jl#253]
This relates to #175, #235 and #243. Apologies if I'm totally wrong, but is the DataFrames package only included so it can be used as a default sink? If that's the case, then perhaps compatibility could be modified to accept any version of DataFrames that supports the Tables.jl interface (i.e. `> X`). It's currently not possible to update DataFrames to the latest version, and since the DataFrames package is updated quite regularly, this might keep happening.

**Comment by quinnj** [comment]
Yeah, for a 1.0 release, I'd like to remove the DataFrames dependency to avoid these kinds of problems.

**Comment by ltf-canada** [comment]
This version is still not compatible with DataFrames 0.21. I realize that there is work in progress to refactor ODBC. In the near term, can something that can be done to allow ODBC to work with the current version of DataFrames?

**Comment by quinnj** [comment]
Ok, backported the DataFrames 0.21 compat in https://github.com/JuliaDatabases/ODBC.jl/commit/3ebc0a8b7c347eac3616a19858d4870980a96da5#commitcomment-39391602; and in master (after #263, the package no longer has a DataFrames dependency)
