### ISSUE TITLE
PostgreSQL connection error: ERROR: IM004: [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed

### ISSUE THREAD

**Issue by gyansinha** [JuliaDatabases/ODBC.jl#298]
I can't seem to get the Postgres connection going. I've added a session log below. Any thoughts on how to proceed further with this error. isql at the command line works fine and I am able to query the

julia> ODBC.adddriver("PostgreSQL", "/usr/lib/x86_64-linux-gnu/libodbc.so";)
1

julia> ODBC.drivers()
Dict{String,String} with 2 entries:
  "ODBC Drivers" => ""
  "PostgreSQL"   => "Driver=/usr/lib/x86_64-linux-gnu/libodbc.so\0UsageCount=1\0"

julia> conn = ODBC.Connection("Driver={PostgreSQL};SERVER=127.0.0.1;USER=****;PWD=****")
ERROR: IM004: [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] driverconnect(::String) at /home/gsinha/.julia/packages/ODBC/IdNGz/src/API.jl:114
 [3] ODBC.Connection(::String, ::Nothing, ::Nothing) at /home/gsinha/.julia/packages/ODBC/IdNGz/src/dbinterface.jl:44
 [4] ODBC.Connection(::String) at /home/gsinha/.julia/packages/ODBC/IdNGz/src/dbinterface.jl:43
 [5] top-level scope at REPL[7]:1

**Comment by quinnj** [comment]
Sorry for the slow reply; can you share what operating system you're using? I can try to setup a similar environment and reproduce the issue. I assume you're on linux? Is it ubuntu? Something else? What version number?

Googling this error seems to indicate there's some kind of permissions problem or more specifically, that the user running the julia process isn't in `/etc/passwd`. It sounds like you can run as root or add the user there. See this link for help: https://github.com/microsoft/msphpsql/issues/400#issuecomment-481722255

**Comment by gyansinha** [comment]
Sorry for not providing environment information earlier but here it is:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

I will try to explore further based on the link you suggested. Thanks.

**Comment by gyansinha** [comment]
I got this figured out - it was a mistake on my part with driver - was passing the wrong shared library into the adddriver function.

This is the sequence of commands I followed:

``
using ODBC     
using DataFrames     
ODBC.adddriver("PostgreSQL Unicode", "/usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so";)
conn = ODBC.Connection("Driver={PostgreSQL Unicode};Server=127.0.0.1;Port=5432;Database=*****;Uid=****Pwd=*****")
@time df = DBInterface.execute(conn, "select * from consumer.panels;") |> DataFrame
``

 8.661387 seconds (20.88 M allocations: 879.005 MiB, 3.50% gc time)
462729×18 DataFrame. Omitted printing of 10 columns

For reference, the same query using pandas.read_sql:
%%timeit

pnl_df = pd.read_sql("select * from consumer.panels", con=initdb.gcm_engine)
5.45 s ± 7.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Thanks for your effort with the package and your help.
