### ISSUE TITLE
Can't read system odbcinst.ini

### ISSUE THREAD

**Issue by akdor1154** [JuliaDatabases/ODBC.jl#300]
Heya, somewhat related to #299 but tangential.
I can't seem to get ODBC.jl to read my system odbcinst.ini.
Reproduction:
```jl
import ODBC
ODBC.setunixODBC(;ODBCSYSINI="/etc", ODBCINSTINI="odbcinst.ini") # from `man unixodbc`
ODBC.drivers()
```
I think I found one bug relating to this that I fixed locally which prevented a crash from the above:
https://github.com/JuliaDatabases/ODBC.jl/blob/72d3354f7fa5bd095654b92c5e9eecfb409635b2/src/API.jl#L198
```diff
-        ENV[k] = v
+        ENV[string(k)] = v
```

however even with this fix ODBC.jl refuses to read my system drivers. Have you ever been able to get this working locally?

**Comment by quinnj** [comment]
<img width="546" alt="Screen Shot 2020-06-12 at 8 23 36 AM" src="https://user-images.githubusercontent.com/2896623/84513041-1ec45580-ac86-11ea-98bb-26614bdcfd91.png">
Yeah, it looks like unixODBC does a permanent cache of the first odbcinst.ini file it reads. But, I also noticed that it will read a USER odbcinst.ini file in addition to the system one, so it worked for me to make a file like `$HOME/.odbcinst.ini`.

In terms of a larger fix, I understand the desire to use an existing system configuration. I think we just need our own `ODBC_JL_USE_SYSTEM_INI` environment variable that will avoid setting any ODBC.jl-specific env variables.

**Comment by akdor1154** [comment]
hey I'm just having a proper play around with this but I'm still having trouble.
I think the overwriting of ENV vars in `setupenv` is still not happening early enough to affect unixodbc's config loading. If I override them manually, however, then I can get it working:
```jl
ENV["OVERRIDE_ODBCJL_CONFIG"] = "true"
ENV["ODBCSYSINI"] = "/etc"
ENV["ODBCINSTINI"] = "odbcinst.ini"
ENV["ODBCINI"] = "/etc/odbc.ini"
```

There are still some open questions I have:
 - if setupenv is incapable of affecting unixODBC's operation in practice, is it worth removing this functionality from setunixodbc(), and just advising that users DIY as above? (i have not investigated whether iodbc and odbc32 have similar limitations).
    - I suspect this is happening because of the `setupenv()` call in `__init__()`, i guess it might be possible to refactor out `__init__` and do it on-demand, but probably a bit fiddly, and tbh DIY seems fine to me as a library consumer, it's a standard pattern.
 - it's a little annoying that the above ODBCINSTINI etc. are required as they are just re-specifying documented defaults of unixodbc. When I use `strace` to see what's going on if I leave them unspecified, it looks like the bundled unixodbc is actually looking in `/workspace/destdir/etc/odbcinst.ini`, I am guessing something funny (missing configure flag?) is going on when unixODBC_jll gets compiled. I'm still working my way around finding where this package even comes from haha.

    it would be good to fix this, i can see two ways:
    - fix unixodbc_jll to look in the default documented system location for its conf files
    - allow users of ODBC.jl to specify at runtime (maybe with OVERRIDE_ODBCJL_CONFIG itself as it's a very similar use-case) to get ODBC.jl to try and link against their system unixodbc.so.. but you had good reason to remove this code-path so I can definitely understand if you don't want to add this back in! also supporting configurable system-unixodbc AND bundled-unixodbc sounds like a good way to double the amount of "how do i configure ODBC?" issues you have to deal with, haha.
