### ISSUE TITLE
Issues setting up connection

### ISSUE THREAD

**Issue by whubbla** [JuliaDatabases/ODBC.jl#312]
Hello.

I have installed ODBC and run this:

`julia> using ODBC`
`julia> ODBC.dsns()`

It successfully lists the dsn I want to use.

I then run statements like those pasted below, where dsnname is listed by ODBC.dsns(), and each fails with ERROR: UndefVarError: Connection not defined.

`julia> conn = ODBC.Connection(dsnname)`
or
`julia> ODBC.Connection(dsnname)`

I'm expecting .Connection() to work based on the documentation here https://juliadatabases.github.io/ODBC.jl/stable/#Troubleshooting-1

I'm running this on Windows with Julia 1.5.

**Comment by quinnj** [comment]
It would seem you're on an older version of ODBC.jl? You can check the version by doing `] st`. To upgrade, you should be able to do `] up ODBC`

**Comment by whubbla** [comment]
I just installed ODBC for the first time a couple weeks ago.  Nevertheless, I ran the upgrade and it has not resolved the issue.

**Comment by whubbla** [comment]
It seems that I had to remove and then explicitly install a later version; it works now, but I am curious why by default it seems to install an older version.

**Comment by quinnj** [comment]
I think it has to do with other packages that may have different compatibility requirements on the same dependencies that ODBC.jl has; i.e. another package may require, for example, an older version of Tables.jl, and the latest ODBC.jl version requires a newer one, so in resolution, it installs the older version of Tables.jl and ODBC.jl (that is compatible w/ the older Tables.j lversion). I don't know the specifics here, but that's an example where it can be tricky to track down exactly why versions are stuck.
