### ISSUE TITLE
Problem with unhandled exceptions

### ISSUE THREAD

**Issue by whubbla** [JuliaDatabases/ODBC.jl#314]
Hello,

I am not certain whether this is an ODBC.jl problem or a debugger problem (or a me problem), but I am experiencing the following:

When I'm running a Julia script in debug mode and choose to break on uncaught exceptions (if I don't choose to do this, then nothing works right, which I think is a debugger issue), then I get stuck in an endless loop of trying to log something (so, no amount of stepping out or over or continuing gets me back to my code) arising from something in ODBC.

Specifically, I run this code:
`conn = ODBC.Connection(dsnname)`

where dsnname is the name of a dsn I set up in Windows.  I'm using Windows login, so no user name or password.

Anyway, it ends up in line 351 of API.jl which has this:
`connect(dsn, user, pwd) = driverconnect(string("DSN=", dsn, user === nothing ? "" : ";UID=$user", pwd === nothing ? "" : ";PWD=$pwd"))`

user and pwd both are nothing, so it should just be passing "DSN=" and the name of my dsn, which is what it looks to be doing.  But for some reason, driverconnect(.) is getting sent to error logging, i.e., the next thing up in the call stack is in base\logging.jl, and that's where my stepping line gets stuck when I'm trying to debug.

```
function driverconnect(connstr)
    dbc = Handle(SQL_HANDLE_DBC, ODBC_ENV[])
    @checksuccess dbc SQLDriverConnect(dbc, connstr)
    return dbc
end
```

Somehow I get stuck in this:
```
# Generate code for logging macros
function logmsg_code(_module, file, line, level, message, exs...)
```

Please let me know if I can give you any more information.

Also, I should note that if I just run the script in the REPL or execute the whole file, it works fine, in the sense that I can create an ODBC connection to MS SQL Server and get data back.

**Comment by quinnj** [comment]
Thanks for the report; yeah, this doesn't sound like an ODBC.jl issue at all. I would suggest copy/pasting this issue to https://github.com/JuliaDebug/Debugger.jl, so people more familiar with that code could help figure out why it seems to be getting confused.
