### ISSUE TITLE
updates of ODBC.jl break ini files

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaDatabases/ODBC.jl#315]
What happens is that since the ini files are stored in `ODBC/config`, when Julia updates ODBC, you are now using a completely different directory where the ini files no longer exist.  Not really that big a deal, given how easy it is to add drivers (I typically do this in the build step of the package I'm building which uses ODBC), however I believe this demonstrates that the project directory is not the proper place for the configs.

I believe the proper thing to do here would be to use the Pkg artifacts API to create an "artifact" directory which would store the ini files.

**Comment by quinnj** [comment]
PR up where we switch to using Scratch.jl for a permanent package location where we can store ini files: https://github.com/JuliaDatabases/ODBC.jl/pull/320
