### ISSUE TITLE
Documentation URL Links Are Incorrect

### ISSUE THREAD

**Issue by bryanso** [JuliaDatabases/ODBC.jl#318]
In the ODBC.jl home page: https://juliadatabases.github.io/ODBC.jl/

The documentation URLs are incorrect.

STABLE is linking to https://juliadb.github.io/ODBC.jl/stable
LATEST is linking to https://juliadb.github.io/ODBC.jl/latest

**Comment by ViralBShah** [comment]
I believe this is now fixed.
