### ISSUE TITLE
BoundsError Issue when converting to DataFrames regression #306

### ISSUE THREAD

**Issue by pankgeorg** [JuliaDatabases/ODBC.jl#328]
#306 

ODBC v1.0.4, julia 1.7
The violating character is `\xce\0`

![image](https://user-images.githubusercontent.com/8681967/134652188-d081f5f8-3218-4498-a52c-176f5d02982a.png)

Branch `jq/fixdec` works normally.
`"Select @@version"` gives
`Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n"`

Update: The violating character is _not_ `\xce\0` that's what the branch `jq/fixdec` shows. The correct string is much weirder, it's

`"Α ΕΛΕΥΘΕΡΩΝ ΕΠΑΓΓΕΛΜΑΤΩΝ ΑΘΗΝΩΝ"` vs `"A ΕΛΕΥΘΕΡΩΝ ΕΠΑΓΓΕΛΜΑΤΩΝ Α\xce\0"`. Collation is `Greek_CI_AS` and max_size = 50.
Most likely this is an encoding issue. The error mentions something about accessing positions 1-59 of string with 50 characters.

**Comment by pankgeorg** [comment]
Update: The violating character is _not_ `\xce\0` that's what the branch `jq/fixdec` shows. The correct string is much weirder, it's

`"Α ΕΛΕΥΘΕΡΩΝ ΕΠΑΓΓΕΛΜΑΤΩΝ ΑΘΗΝΩΝ"` vs `"A ΕΛΕΥΘΕΡΩΝ ΕΠΑΓΓΕΛΜΑΤΩΝ Α\xce\0"`

**Comment by quinnj** [comment]
I've opened the PR again; but you're saying it doesn't fix the issue?

**Comment by pankgeorg** [comment]
> I've opened the PR again; but you're saying it doesn't fix the issue?

It does work with the PR, meaning it doesn't explode, but it returns a truncated version of the string. I think there is an underlying encoding issue.

**Comment by jakobnissen** [comment]
I've just hit this issue. The string that triggers it is "Lokalt prøvenr.:  IKKE ANGIVET Uoplyst prøvetagningsdato Overføres til konto 65", and the index error is `ERROR: BoundsError: attempt to access 81-element Vector{UInt8} at index [1:82]`. Indeed, there are 82 codeunits in the string. So the issue must be that somehow, not enough space is allocated to the string.

**Comment by jakobnissen** [comment]
Bump - is there any MWE or similar I can provide to have this resolved?
By the way, changing line 355 in `dbinterface.jl` from `bytes = data[1:b.totallen]` to `bytes = data[1:min(length(data), b.totallen)]` means it no longer errors. Instead, however, the string listed above is truncated to `"Lokalt prøvenr.:  IKKE ANGIVET Uoplyst prøvetagningsdato Overføres til konto \0"`. No idea where the null byte at the end come from.
