### ISSUE TITLE
When importing ODBC module, the core crashes

### ISSUE THREAD

**Issue by luping-lup** [JuliaDatabases/ODBC.jl#331]
When importing ODBC module, the core crashes. Other modules can work normally.

julia> using ODBC
LLVM ERROR: Unsupported calling convention.

signal (6): Aborted
in expression starting at REPL[1]:1
gsignal at /lib64/libc.so.6 (unknown line)
abort at /lib64/libc.so.6 (unknown line)
_ZN4llvm18report_fatal_errorERKNS_5TwineEb at /sim8/bin/../lib/julia/libLLVM-12jl.so (unknown line)
_ZN4llvm18report_fatal_errorERKNS_5TwineEb at /sim8/bin/../lib/julia/libLLVM-12jl.so (unknown line)
Allocations: 725435 (Pool: 725022; Big: 413); GC: 1
Aborted (core dumped)

**Comment by quinnj** [comment]
Hmmm, can you confirm what Julia version, OS, ODBC.jl version you're on?

**Comment by quinnj** [comment]
I'm actually in the process of receiving an M1 machine (in the next few weeks), so I should hopefully be able to help more directly here soon. Sorry for the wait/delay!

**Comment by quinnj** [comment]
This should be fixed.
