### ISSUE TITLE
Failed to precompile Julia v1.7.2 on Mac (M1)

### ISSUE THREAD

**Issue by haavardhvarnes** [JuliaDatabases/ODBC.jl#335]
Hi,

Not programming a lot, but building/precompiling fails and I am out of options. I have used ODBC.jl before on same computer but on Julia 1.6 and 1.5

Stack trace is (same error from "clean" install): 
julia> using ODBC
[ Info: Precompiling ODBC [be6f12e9-ca4f-5eb2-a339-a4f995cc0291]
ERROR: LoadError: UndefVarError: libodbc not defined
Stacktrace:
  [1] getproperty(x::Module, f::Symbol)
    @ Base ./Base.jl:35
  [2] top-level scope
    @ ~/.julia/packages/ODBC/qhwMX/src/API.jl:4

Any ideas?

**Comment by quinnj** [comment]
ODBC.jl relies on a few pre-built binary shared libraries being available/compiled for supported systems in order to run. So it's a bit stuck if those aren't supported. I'll try to track down those dependencies and see if it's possible to support the new M1 systems.

**Comment by bobcassels** [comment]
I'm having the same problem. Works fine in Julia 1.7.2 on my older Intel Mac. I'll try @quinnj 's notion of downgrading to Julia 1.6. (Thanks!)

**Comment by bobcassels** [comment]
Hey @quinnj — If there's something I can do to help, please let me know. I'm trying to introduce Julia into the company I just joined, but the fact that I'm having problems is giving the Python advocates anti-Julia ammunition. For security reasons, I must use the company-supplied M1 Mac.

**Comment by quinnj** [comment]
It might be because the ODBC shared libraries we're dependent on aren't M1-compatible yet (@giordano might know better). I've also heard it's possible to "run under rosetta" on M1s to get backwards compatibility with libraries that haven't upgraded yet, so that might be worth a try. Sorry to not be more helpful, but I don't have an M1 at the moment and can only relay what I've heard other users saying.

**Comment by giordano** [comment]
This issue can be closed, but there is a different problem when loading the package, which kills the Julia process. This is likely due to a slightly incorrect use of `ccall`, but I don't have the time to dig this further. See #338 for more details.
