### ISSUE TITLE
Prevent SQL injection (prepared statement + escape meta)

### ISSUE THREAD

**Issue by bluesmoon** [JuliaDatabases/ODBC.jl#74]
[mirrored from https://groups.google.com/d/msg/julia-users/fRFr20atCbc/SqUVy8kvwdAJ]

This is an extension of Issue #15 which already covers prepared statements.

I'm using the `ODBC` package to connect to a database and make a few SQL queries.  For some of these queries, the table name or values in the `WHERE` clause come from variables, and I need a way to safely quote them for use in an SQL string.

For values in the `WHERE` clause, prepared statements will help get rid of SQL injection.

For table names (and column names as well), a simple sql escape function would help (one that is database character set aware).  Something similar to PHP's `mysqli_real_escape_string`: http://php.net/manual/en/mysqli.real-escape-string.php

**Comment by quinnj** [comment]
We now have full prepared statement support as of #263 ; and ODBC provides a common escaping mechanism that all drivers must implement.
